- name: app-setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: java-setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yaml

- name: install mysql pymsql library dependencies
  ansible.builtin.pip:
    name: "{{ item }}" 
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: import mysql
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ LOGIN_HOST }}"
    login_user: "{{ LOGIN_USER }}"
    login_password: "{{ LOGIN_PASSWORD }}"
    target: "{{ item }}"
  loop: 
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: system-setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml